require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - .rubocop_common.yml

RSpec/Focus:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*.rb'

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedExample:
  Exclude:
    - 'spec/policies/**/*.rb'

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'test/*'
    - 'db/migrate/*.rb'
    - '**/*.jbuilder'
    - bin/**/*
    - tmp/**/*
    - config/initializers/simple_form.rb
    - config/initializers/simple_form_bootstrap.rb
    - node_modules/**/*