require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/board_sections", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BoardSection. As you add validations to BoardSection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BoardSection.create! valid_attributes
      get board_sections_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      board_section = BoardSection.create! valid_attributes
      get board_section_url(board_section)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_board_section_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      board_section = BoardSection.create! valid_attributes
      get edit_board_section_url(board_section)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BoardSection" do
        expect {
          post board_sections_url, params: { board_section: valid_attributes }
        }.to change(BoardSection, :count).by(1)
      end

      it "redirects to the created board_section" do
        post board_sections_url, params: { board_section: valid_attributes }
        expect(response).to redirect_to(board_section_url(BoardSection.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BoardSection" do
        expect {
          post board_sections_url, params: { board_section: invalid_attributes }
        }.to change(BoardSection, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post board_sections_url, params: { board_section: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested board_section" do
        board_section = BoardSection.create! valid_attributes
        patch board_section_url(board_section), params: { board_section: new_attributes }
        board_section.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the board_section" do
        board_section = BoardSection.create! valid_attributes
        patch board_section_url(board_section), params: { board_section: new_attributes }
        board_section.reload
        expect(response).to redirect_to(board_section_url(board_section))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        board_section = BoardSection.create! valid_attributes
        patch board_section_url(board_section), params: { board_section: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested board_section" do
      board_section = BoardSection.create! valid_attributes
      expect {
        delete board_section_url(board_section)
      }.to change(BoardSection, :count).by(-1)
    end

    it "redirects to the board_sections list" do
      board_section = BoardSection.create! valid_attributes
      delete board_section_url(board_section)
      expect(response).to redirect_to(board_sections_url)
    end
  end
end
