name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - develop

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: pinmapper
          POSTGRES_PASSWORD: pinmapper
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby 2.7.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler-cache: true

      - name: Setup Node 15
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile

      - name: Run tests
        env:
          DATABASE_URL: postgres://pinmapper:pinmapper@localhost:5432/pinmapper_test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PG_USER: pinmapper
        run: |
          bin/rails db:test:prepare
          bin/rails test